name: Apply Repository Settings

on:
  push:
    branches:
      - main

jobs:
  apply-settings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Apply settings
        run: |
          # Use a script or tool to apply settings
          github-settings apply --file .settings.yml
